sudo: false
os:
  - linux

dist:
  - trusty

language: rust

rust:
  - 1.21.0
  - 1.22.1
  - 1.23.0
  - 1.24.0
  - 1.25.1
  - 1.26.0
  - 1.27.0
  - 1.28.0
  - 1.29.0
  - 1.30.0
  - 1.31.0
  - 1.32.0
  - 1.33.0
  - 1.34.0
  - 1.35.0
  - 1.36.0
  - 1.37.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true

script:
  - |
    cargo build --all --all-features -j 1 || exit 1
    cargo test  --all --all-features -j 1 || exit 1

notifications:
  email:
    on_success: never
  irc:
    channels:
      - chat.freenode.net#imag
    template:
      - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"


