sudo: false
os:
  - linux

dist:
  - trusty

language: rust

rust:
  - 1.21.0
  - 1.22.1
  - 1.23.0
  - 1.24.0
  - 1.25.0
  - 1.26.2
  - 1.27.2
  - 1.28.0
  - 1.29.2
  - 1.40.0
  - 1.41.1
  - 1.42.0
  - 1.43.1
  - 1.44.1
  - 1.45.2
  - 1.46.0
  - 1.47.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  cargo: true

script:
  - |
    cargo build --all --all-features -j 1 || exit 1
    cargo test  --all --all-features -j 1 || exit 1

notifications:
  email:
    on_success: never
  irc:
    channels:
      - chat.freenode.net#imag
    template:
      - "%{repository_name} (%{branch} @ %{commit} by %{author}): %{result}"


